plugins {
    id 'groovy'
    id 'org.springframework.boot' version '3.5.5'
}

group = 'com.vendavo.eps'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:3.5.5'
    testImplementation 'org.spockframework:spock-core:2.4-M6-groovy-4.0'
    testImplementation 'org.apache.groovy:groovy:4.0.28'
    testImplementation 'org.mockito:mockito-core:5.19.0'
}

test {
    useJUnitPlatform()
}